version: "3.8"
services:
  nngs:
    build: .

    # 起動しっぱなしにします。
    tty: true
    
    environment:
      # Git hub にアクセスできるユーザー名、Eメールを環境変数に指定してください。
      - NNGS_GIT_USER_NAME
      - NNGS_GIT_USER_EMAIL

    expose:
#      - "6969"
      - "9696"
    ports:
      - "6969:6969"
      - "9696:9696"
